### ISSUE TITLE
Reconnect device after reboot

### ISSUE THREAD

**Issue by fvisticot** [weliem/blessed-android#8]
Is there any methods in the library to reconnect the device after reboot.
On iOS it is possible so you library could try to implement this usefull feature.
If it is not in the roadmap, can you please advice how to implement this taking into account new Android 10 constraints related to BLE (no background service if I'm correct)

**Comment by weliem** [comment]
Well, the only thing the library provides current is a method to 'autoconnect' to a device when it is found:
autoConnectPeripheral(BluetoothPeripheral peripheral, BluetoothPeripheralCallback peripheralCallback)

However, the app needs to be running in order to issue this call. If you want to connect to devices at boot time you will need to create a Foreground service that starts your code. Then you can issue the autoconnect.

I am not aware of any new Android 10 restrictions on BLE. Do you have more information or a link?
